# This is my Iosevka Fixed Custom font
# The goal is to get close to the size of the following font
# - Misc-Fixed-medium-R-*-*-13-120-75-75-C-120-ISO10646-1
[buildPlans.IosevkaFixedCustom]
family = "Iosevka Fixed Custom"
spacing = "fixed"
serifs = "sans"
noLigation = true # Fixed by defintion doesn't have ligation
noCvSs = true
exportGlyphNames = false # Useful for terminals like Kitty
outFormat = ["ttf"] # Only generte the standard desktop fonts

[buildPlans.IosevkaFixedCustom.variants.design]
zero = "tall-slashed"  # Prefer Zero with a slash
one = "base" # One with a base and slant
l = "serifed-flat-tailed"   # Better legibility for 'l'

[buildPlans.IosevkaFixedCustom.metricOverride]
leading = 1000    # Tightest vertical spacing
cap = 700         # Shorter caps
xheight = 510     # Balanced lowercase

[buildPlans.IosevkaFixedCustom.widths.Normal]
shape = 480       # Extremely narrow, matching fixed 6x13
menu = 5
css = "normal"

[buildPlans.IosevkaFixedCustom.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaFixedCustom.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaFixedCustom.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaFixedCustom.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

# To enable TTC building, uncomment the following section and write your collect plans
[collectPlans.IosevkaFixedCustom]
from = ["IosevkaFixedCustom"]
